# Generated by Django 5.2.4 on 2025-07-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='description',
            field=models.TextField(default='descriptions', max_length=250),
        ),
        migrations.AddField(
            model_name='ad',
            name='image_url',
            field=models.ImageField(default=None, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='ad',
            name='title',
            field=models.CharField(default='title', max_length=50),
        ),
    ]
