# Generated by Django 5.2.4 on 2025-07-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_exchangeproposal_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='condition',
            field=models.CharField(choices=[('Новый', 'New'), ('Б/У', 'Used')], default='Новый', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalad',
            name='condition',
            field=models.CharField(choices=[('Новый', 'New'), ('Б/У', 'Used')], default='Новый', max_length=10),
        ),
    ]
